# -*- coding: utf-8 -*-
"""None, true.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ridusRC-2JJhWg9Hi5n342Bc1Vk_yW3Z
"""

import pandas as pd
import numpy as np
import zipfile
import os
from sentence_transformers import SentenceTransformer
from numpy.linalg import norm

# Load SBERT model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Load and embed verses
df_aranya = pd.read_csv('All_Kandas.csv')
df_aranya['embedding'] = df_aranya['English Translation'].apply(lambda x: model.encode(str(x)))

# Matching function
def match_statement(user_input, df, threshold_true=0.75, threshold_none=0.4):
    user_embedding = model.encode(user_input)
    similarities = [
        np.dot(user_embedding, emb) / (norm(user_embedding) * norm(emb))
        for emb in df['embedding']
    ]
    max_similarity = max(similarities)
    best_index = similarities.index(max_similarity)
    best_row = df.iloc[best_index]

    if max_similarity >= threshold_true:
        return {
            "result": True,
            "similarity": round(max_similarity, 3),
            "source": {
                "Kanda/Book": best_row['Kanda/Book'],
                "Sarga/Chapter": best_row['Sarga/Chapter'],
                "Shloka/Verse": best_row['Shloka/Verse'],
                "English Translation": best_row['English Translation']
            }
        }
    elif max_similarity >= threshold_none:
        return {"result": False, "similarity": round(max_similarity, 3)}
    else:
        return {"result": None, "similarity": round(max_similarity, 3)}

# Extract ZIP
zip_path = "ramayana_statements_10_csvs_full.zip"
extract_dir = "extracted_csvs"
os.makedirs(extract_dir, exist_ok=True)
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

# Process each CSV file inside the ZIP
for csv_file in os.listdir(extract_dir):
    if csv_file.endswith(".csv"):
        df_tests = pd.read_csv(os.path.join(extract_dir, csv_file))
        print(f"\n--- Processing file: {csv_file} ---")
        for idx, row in df_tests.iterrows():
            print(f"Test ID {idx + 1}: {row['statement']}")
            result = match_statement(row['statement'], df_aranya)
            print("Expected Truth:", row['truth_value'])
            print("Match Result:", result)
            print("-" * 60)

