# -*- coding: utf-8 -*-
"""Ramayana_Verses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFN-j28Pf67YDEqc2q5xmSd74TDMzXDe

To scrape all the verses of different kandas
 1. First, set the range of sargas of respective kandas. We initialized the headers as "Kanda/Book, Sarga/Chapter, Shloka/Verse, English Translation"
 2. Then, iterate a loop over all the Sargas URLs using the libraries BeautifulSoup, requests, and pandas for data frames and CSV.
 3. Sending requests and checking the status code of each url if the code is 200 it will move further or else it will give http error which means URL is different from other.
 4. As URLs of sarga 25 and 40 of each kanda is different from other it has to be scraped differently and merged with main raw csv.
 5. The Kandas Ayodhya, Sundara, and Yuddha were to be scraped differently from other kandas because it does not have shloka numbers at the end of the verse, and the shloka numbers were extracted from another tag from pratipada, from which it separates the shloka number and saves it.
 6. Next, we have done the cleaning by removing all special characters, extra double quotes, and corrected some of the sarga numbers that were printed mistakenly on the website.
 7. At last, we merged all Kandas CSVs and created a final dataset.
 8. This cleaned and structured data is tested for tasks like search, Matching and analysis using models like SBERT.
"""

import requests                           # For making HTTP requests to fetch web pages
from bs4 import BeautifulSoup             # For parsing HTML content
import pandas as pd                       # For handling data structures (not used directly here but useful)
import csv                                # For writing CSV files
import time                               # For adding delays between requests
from urllib.parse import urljoin          # For combining base and relative URLs
import re                                 # For regex operations (e.g., extracting verse numbers)
import os                                 # For directory operations

# creating a folder to save all kandas in one folder
output_dir = "ramayan_kandas_csv"
os.makedirs(output_dir, exist_ok=True)

# Dictionary storing metadata for each Kanda: folder name, file prefix, sarga range, and special URLs
kandas = {
    'Bala': {
        'folder': 'baala',
        'file_prefix': 'bala',
        'start': 1,
        'end': 77,
        'special_urls': {  # Some sargas have different URL like for 25 and 40
            25: 'https://www.valmikiramayan.net/utf8/baala/sarga25/bala_5F25_frame.htm',
            40: 'https://www.valmikiramayan.net/utf8/baala/sarga40/bala_5F40_frame.htm',
        }
    },
    # Same structure for remaining kandas
    'Ayodhya': {
        'folder': 'ayodhya',
        'file_prefix': 'ayodhya',
        'start': 1,
        'end': 119,
        'special_urls': {
            25: 'https://www.valmikiramayan.net/utf8/ayodhya/sarga25/ayodhya_5F25_frame.htm',
            40: 'https://www.valmikiramayan.net/utf8/ayodhya/sarga40/ayodhya_5F40_frame.htm',
        }
    },
    'Aranya': {
        'folder': 'aranya',
        'file_prefix': 'aranya',
        'start': 1,
        'end': 75,
        'special_urls': {
            25: 'https://www.valmikiramayan.net/utf8/aranya/sarga25/aranya_5F25_frame.htm',
            40: 'https://www.valmikiramayan.net/utf8/aranya/sarga40/aranya_5F40_frame.htm',
        }
    },
    'Kishkindha': {
        'folder': 'kish',
        'file_prefix': 'kishkindha',
        'start': 1,
        'end': 67,
        'special_urls': {
            25: 'https://www.valmikiramayan.net/utf8/kish/sarga25/kishkindha_5F25_frame.htm',
            40: 'https://www.valmikiramayan.net/utf8/kish/sarga40/kishkindha_5F40_frame.htm',
        }
    },
    'Sundara': {
        'folder': 'sundara',
        'file_prefix': 'sundara',
        'start': 1,
        'end': 68,
        'special_urls': {
            25: 'https://www.valmikiramayan.net/utf8/sundara/sarga25/sundara_5F25_frame.htm',
            40: 'https://www.valmikiramayan.net/utf8/sundara/sarga40/sundara_5F40_frame.htm',
        }
    },
    'Yuddha': {
        'folder': 'yuddha',
        'file_prefix': 'yuddha',
        'start': 1,
        'end': 128,
        'special_urls': {
            25: 'https://www.valmikiramayan.net/utf8/yuddha/sarga25/yuddha_5F25_frame.htm',
            40: 'https://www.valmikiramayan.net/utf8/yuddha/sarga40/yuddha_5F40_frame.htm',
        }
    },
}

# Headers for output file
header = ['Kanda/Book', 'Sarga/Chapter', 'Shloka/Verse', 'English Translation']

# Function to scrape a single sarga/ chapter from the provided frame page URL
def scrape_sarga(kanda_name, folder, file_prefix, sarga, frame_page_url, writer):
    try:
        response = requests.get(frame_page_url)                 # Request the outer frame page
        response.raise_for_status()                             # Raise error if HTTP request failed
        soup = BeautifulSoup(response.text, 'html.parser')      # Parse HTML content

        frame = soup.find('frame', {'name': 'main'})            # Extract the 'main' frame containing actual verse content
        if not frame:
            print(f"{kanda_name} Sarga {sarga}: Frame not found")
            return 0

        frame_src = frame.get('src')                            # Get source URL of the main frame
        frame_url = urljoin(frame_page_url, frame_src)          # Build full URL of the main frame

        frame_response = requests.get(frame_url)                # Request main frame content
        frame_response.raise_for_status()
        frame_soup = BeautifulSoup(frame_response.text, 'html.parser')

        pratipada_tags = frame_soup.find_all('p', class_='pratipada')  # pratipada tags for extracting shloka numbers
        tat_tags = frame_soup.find_all('p', class_='tat')              # English translation tags

        count = 0
        for p_tag, t_tag in zip(pratipada_tags, tat_tags):      # Loop through each verse and its translation
            em_tag = p_tag.find('em')                           # Extract verse number from <em> tag
            if em_tag:
                matches = re.findall(r'\d+[a-zA-Z]?', em_tag.text.strip())  # Extract number like 1, 1a, 2b, etc.
                if matches:
                    shloka_number = ",".join(matches)           # Join multiple verse numbers if present
                    verse_text = t_tag.get_text(strip=True)     # Extract English translation text
                    writer.writerow([kanda_name, sarga, shloka_number, verse_text])  # Write row to CSV
                    count += 1

        print(f"{kanda_name} Sarga {sarga}: {count} verses written")  # Print progress
        return count

    except Exception as e:
        print(f"{kanda_name} Sarga {sarga}: Error - {e}")        # Print error message if any
        return 0

# Function to scrape all sargas of a given kanda
def scrape_kanda(kanda_name, kanda_info):
    csv_path = os.path.join(output_dir, f'{kanda_name.lower()}kanda_verses.csv')  # Output CSV path
    with open(csv_path, mode='w', newline='', encoding='utf-8') as file:         # Open CSV file
        writer = csv.writer(file)
        writer.writerow(header)                                                  # Write header row

        for sarga in range(kanda_info['start'], kanda_info['end'] + 1):          # Loop through each sarga
            if sarga in kanda_info['special_urls']:                              # Use special URL if present
                url = kanda_info['special_urls'][sarga]
            else:
                url = f"https://www.valmikiramayan.net/utf8/{kanda_info['folder']}/sarga{sarga}/{kanda_info['file_prefix']}_{sarga}_frame.htm"  # Construct standard URL

            scrape_sarga(kanda_name, kanda_info['folder'], kanda_info['file_prefix'], sarga, url, writer)  # Scrape sarga
            time.sleep(1)  # Delay to avoid server overload

    print(f"Downloaded: {csv_path}")  # Completion message

# Main script entry point — loops through all kandas and scrapes them
if __name__ == "__main__":
    for kanda_name, kanda_info in kandas.items():  # Iterate through all kandas defined
        print(f"Processing {kanda_name} Kanda...")  # Print progress
        scrape_kanda(kanda_name, kanda_info)        # Call scraping function for this kanda

import pandas as pd  # Importing pandas library for data manipulation and analysis

# List of input CSV filenames in the order
file_list = [
    "balakanda_verses.csv",
    "ayodhyakanda_verses.csv",
    "aranyakanda_verses.csv",
    "kishkindhakanda_verses.csv",
    "sundarakanda_verses.csv",
    "yuddhakanda_verses.csv"
]

# Define the columns only which have to be included
required_columns = ['Kanda/Book', 'Sarga/Chapter', 'Shloka/Verse', 'English Translation']

# Create an empty list to store cleaned DataFrames
cleaned_data = []

# Loop through each file in the list to read, clean, and store its data
for file in file_list:
    try:
        # Read the CSV file into a DataFrame
        df = pd.read_csv(file)

        # Check if all required columns are present in the current DataFrame
        if all(col in df.columns for col in required_columns):
            # Ensure the 'English Translation' column is of string type
            df['English Translation'] = df['English Translation'].astype(str)

            # Remove extra spaces, newlines, and tabs using regex
            df['English Translation'] = df['English Translation'].str.replace(r'\s+', ' ', regex=True).str.strip()

            # Keep only the required columns and preserve their order
            df = df[required_columns]

            # Add the cleaned DataFrame to the list
            cleaned_data.append(df)
        else:
            # Print warning if any required column is missing
            print(f"Skipping {file}: missing required columns.")
    except Exception as e:
        # if any errors occur, print them
        print(f"Error processing {file}: {e}")

# After processing all files, check if we have any cleaned data to merge
if cleaned_data:
    # merge all cleaned DataFrames into one
    merged_df = pd.concat(cleaned_data, ignore_index=True)

    # Export the merged DataFrame to a new CSV file
    merged_df.to_csv("All_Kandas.csv", index=False, encoding='utf-8')

    print('All_Kandas.csv')
else:
    # If no valid data was there
    print("No valid data to merge.")

