# -*- coding: utf-8 -*-
"""SBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13BEtN1sJ0Dxy2tTazKcTsGYvCs3C2hOL

1. Read the CSV file: Load the file All_Kandas.csv which contains all verses and their English translations in columns: Kanda/Book, Sarga/Chapter, Shloka/Verse, and English Translation.

2. Load the SBERT model: Use the sentence transformer model paraphrase-MiniLM-L6-v2. This model turns English sentences into embeddings—lists of numbers that capture sentence meaning.

3. Convert verses to embeddings: For each verse in the file, use the SBERT model to convert the English Translation into an embedding (768-dimensional vector) and store this embedding in a new column called embedding.

4. Take user input: Ask the user to enter a sentence. Convert this sentence into an embedding using the same SBERT model.

5. Compare with all verses: For every verse in the CSV, calculate the cosine similarity between the user’s embedding and the verse’s embedding. Cosine similarity tells how similar the two meanings are (closer to 1 means more similar).

6. Find the best match: Identify the verse that has the highest similarity score with the user’s sentence.
Decide match quality:

7. If the similarity score is above 0.7, it's a strong match → label as True.

8. If it's between 0.4 and 0.7, it's a weak or partial match → label as False.

9. If it's below 0.4, it's not a match → label as None.

10. Show the result: Display the match result (True, None, or False). If a good match is found, also show the corresponding verse’s Kanda/Book, Sarga/Chapter, Shloka/Verse, and English Translation.

Source: open source (pankaj yadav github), sitare chatbot.https://github.com/pankajyadav8523/Sitare-Chatbot
"""

import pandas as pd
import numpy as np   # For numerical operations
from sentence_transformers import SentenceTransformer  # For loading SBERT model
from numpy.linalg import norm  # For computing vector norms

# Ramayana verses into a dataFrame
df_aranya = pd.read_csv('All_Kandas.csv')

# Loading the pre-trained SBERT model for sentence embeddings
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Create SBERT embeddings for each verse in the Ramayana dataset
# This converts each English verse into a fixed-length vector
df_aranya['embedding'] = df_aranya['English Translation'].apply(lambda x: model.encode(str(x)))

# Define a function that matches a user-input statement with the closest verse in the dataset
def match_statement(user_input, df, threshold_true=0.7, threshold_none=0.4):
    # Encode the user input into a vector
    user_embedding = model.encode(user_input)

    # Compute cosine similarity between the input and all verses in the dataset
    similarities = [
        np.dot(user_embedding, emb) / (norm(user_embedding) * norm(emb))
        for emb in df['embedding']
    ]

    # Find the verse with the highest similarity
    max_similarity = max(similarities)
    best_index = similarities.index(max_similarity)
    best_row = df.iloc[best_index]

    # If similarity exceeds the 'true' threshold, return result as TRUE along with source verse
    if max_similarity >= threshold_true:
        return {
            "result": True,
            "similarity": round(max_similarity, 3),
            "source": {
                "Kanda/Book": best_row['Kanda/Book'],
                "Sarga/Chapter": best_row['Sarga/Chapter'],
                "Shloka/Verse": best_row['Shloka/Verse'],
                "English Translation": best_row['English Translation']
            }
        }
    # If similarity is between lower threshold and true threshold, return as FALSE
    elif max_similarity >= threshold_none:
        return {"result": False, "similarity": round(max_similarity, 3)}
    # If similarity is very low, return as None (no match)
    else:
        return {"result": None, "similarity": round(max_similarity, 3)}

# Giving set of statements with their reference and truth values
test_statements = [
    {"ID":1, "Statement":"Rama is the eldest son of King Dasharatha.", "Truth":"TRUE", "Reference":"Bala Kanda, Chapter 18, Verse 24"},
    {"ID":2, "Statement":"Sita was discovered by King Janaka in a furrow during ploughing and was later adopted by him.", "Truth":"TRUE", "Reference":"Bala Kanda, Chapter 66, Verse 14"},
    {"ID":3, "Statement":"Lakshmana, Rama’s devoted younger brother, accompanied him into exile.", "Truth":"TRUE", "Reference":"Ayodhya Kanda, Chapter 31, Verse 30"},
    {"ID":4, "Statement":"Bharata, another brother of Rama, revered him and ruled as regent in his absence.", "Truth":"TRUE", "Reference":"Ayodhya Kanda, Chapter 115, Verse 22"},
    {"ID":5, "Statement":"Hanuman was the best minister of Sugreeva.", "Truth":"TRUE", "Reference":"Kishkindha Kanda, Chapter 6, Verse 2"},
    {"ID":6, "Statement":"Ravana, the demon king of Lanka, abducted Sita, setting in motion the events of the epic.", "Truth":"TRUE", "Reference":"Aranya Kanda, Chapter 49, Verse 20"},
    {"ID":7, "Statement":"On seeing Hanuman, Sita lost her consciousness for a long time.", "Truth":"TRUE", "Reference":"Sundara Kanda, Chapter 32, Verse 8"},
    {"ID":8, "Statement":"Nila, a general of the monkey army, was rendered unconscious by a mystic arrow shot by Ravana.", "Truth":"TRUE", "Reference":"Yuddha Kanda, Chapter 59, Verse 89"},
    {"ID":9, "Statement":"Nala constructed a bridge for Rama to cross over to Lanka.", "Truth":"TRUE", "Reference":"Yuddha Kanda, Chapter 27, Verse 61"},
    {"ID":10, "Statement":"The sage Vishwamitra mentored Rama during his early life, imparting knowledge of warfare and ritual.", "Truth":"TRUE", "Reference":"Bala Kanda, Chapter 22"},
    {"ID":11, "Statement":"Sita herself built the bridge to Lanka with the help of the monkey army.", "Truth":"FALSE", "Reference":""},
    {"ID":12, "Statement":"Lakshmana was a disciple of Ravana and learned warfare techniques from him.", "Truth":"FALSE", "Reference":""},
    {"ID":13, "Statement":"Bharata was originally from Lanka and was later adopted by King Dasharatha.", "Truth":"FALSE", "Reference":""},
    {"ID":14, "Statement":"After meeting Sita, Hanuman lost his ability to speak entirely.", "Truth":"FALSE", "Reference":""},
    {"ID":15, "Statement":"Ravana is depicted solely as a peaceful poet who never engaged in any battles.", "Truth":"FALSE", "Reference":""},
    {"ID":16, "Statement":"Rama’s exile lasted only one year rather than the traditionally recounted fourteen years.", "Truth":"FALSE", "Reference":""},
    {"ID":17, "Statement":"Sita and Rama were married in Lanka with Ravana acting as the priest for their wedding.", "Truth":"FALSE", "Reference":""},
    {"ID":18, "Statement":"Lakshmana is not mentioned at all in the Valmiki Ramayana.", "Truth":"FALSE", "Reference":""},
    {"ID":19, "Statement":"Bharata built a grand palace in Lanka following Rama’s victory over Ravana.", "Truth":"FALSE", "Reference":""},
    {"ID":20, "Statement":"Hanuman was the son of Ravana.", "Truth":"FALSE", "Reference":""},
]

# Convert the list of test statements to a DataFrame for easier handling
df_tests = pd.DataFrame(test_statements)

# Loop over each test statement
for idx, row in df_tests.iterrows():
    print(f"Test ID {row['ID']}: {row['Statement']}")  # Show which statement is being tested

    # Run the statement through the matcher
    result = match_statement(row['Statement'], df_aranya)

    # Print the expected result and the system's predicted result
    print("Expected Truth:", row['Truth'])
    print("Match Result:", result)
    print("-" * 60)  # Visual separator for readability

import pandas as pd
import numpy as np   # For numerical operations
from sentence_transformers import SentenceTransformer  # For loading SBERT model
from numpy.linalg import norm  # For computing vector norms

# Ramayana verses into a dataFrame
df_aranya = pd.read_csv('All_Kandas.csv')

# Loading the pre-trained SBERT model for sentence embeddings
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Create SBERT embeddings for each verse in the Ramayana dataset
# This converts each English verse into a fixed-length vector
df_aranya['embedding'] = df_aranya['English Translation'].apply(lambda x: model.encode(str(x)))

# Define a function that matches a user-input statement with the closest verse in the dataset
def match_statement(user_input, df, threshold_true=0.693, threshold_none=0.4):
    # Encode the user input into a vector
    user_embedding = model.encode(user_input)

    # Compute cosine similarity between the input and all verses in the dataset
    similarities = [
        np.dot(user_embedding, emb) / (norm(user_embedding) * norm(emb))
        for emb in df['embedding']
    ]

    # Find the verse with the highest similarity
    max_similarity = max(similarities)
    best_index = similarities.index(max_similarity)
    best_row = df.iloc[best_index]

    # If similarity exceeds the 'true' threshold, return result as TRUE along with source verse
    if max_similarity >= threshold_true:
        return {
            "result": True,
            "similarity": round(max_similarity, 3),
            "source": {
                "Kanda/Book": best_row['Kanda/Book'],
                "Sarga/Chapter": best_row['Sarga/Chapter'],
                "Shloka/Verse": best_row['Shloka/Verse'],
                "English Translation": best_row['English Translation']
            }
        }
    # If similarity is between lower threshold and true threshold, return as FALSE
    elif max_similarity >= threshold_none:
        return {"result": False, "similarity": round(max_similarity, 3)}
    # If similarity is very low, return as None (no match)
    else:
        return {"result": None, "similarity": round(max_similarity, 3)}


test_statements = [
    {"ID": 1, "Statement": "Rama is the eldest son of King Dasharatha.", "Truth": "TRUE", "Reference": "Bala Kanda, Chapter 18, Verse 24"},
    {"ID": 2, "Statement": "Sita was discovered by King Janaka in a furrow during ploughing and was later adopted by him.", "Truth": "TRUE", "Reference": "Bala Kanda, Chapter 66, Verse 14"},
    {"ID": 3, "Statement": "Lakshmana, Rama’s devoted younger brother, accompanied him into exile.", "Truth": "TRUE", "Reference": "Ayodhya Kanda, Chapter 31, Verse 30"},
    {"ID": 4, "Statement": "Bharata, another brother of Rama, revered him and ruled as regent in his absence.", "Truth": "TRUE", "Reference": "Ayodhya Kanda, Chapter 115, Verse 22"},
    {"ID": 5, "Statement": "Hanuman was the best minister of Sugreeva.", "Truth": "TRUE", "Reference": "Kishkindha Kanda, Chapter 6, Verse 2"},
    {"ID": 6, "Statement": "Ravana, the demon king of Lanka, abducted Sita, setting in motion the events of the epic.", "Truth": "TRUE", "Reference": "Aranya Kanda, Chapter 49, Verse 20"},
    {"ID": 7, "Statement": "On seeing Hanuman, Sita lost her consciousness for a long time.", "Truth": "TRUE", "Reference": "Sundara Kanda, Chapter 32, Verse 8"},
    {"ID": 8, "Statement": "Nila, a general of the monkey army, was rendered unconscious by a mystic arrow shot by Ravana.", "Truth": "TRUE", "Reference": "Yuddha Kanda, Chapter 59, Verse 89"},
    {"ID": 9, "Statement": "Nala constructed a bridge for Rama to cross over to Lanka.", "Truth": "TRUE", "Reference": "Yuddha Kanda, Chapter 27, Verse 61"},
    {"ID": 10, "Statement": "The sage Vishwamitra mentored Rama during his early life, imparting knowledge of warfare and ritual.", "Truth": "TRUE", "Reference": "Bala Kanda, Chapter 22"},
    {"ID": 11, "Statement": "Sita herself built the bridge to Lanka with the help of the monkey army.", "Truth": "FALSE", "Reference": ""},
    {"ID": 12, "Statement": "Lakshmana was a disciple of Ravana and learned warfare techniques from him.", "Truth": "FALSE", "Reference": ""},
    {"ID": 13, "Statement": "Bharata was originally from Lanka and was later adopted by King Dasharatha.", "Truth": "FALSE", "Reference": ""},
    {"ID": 14, "Statement": "After meeting Sita, Hanuman lost his ability to speak entirely.", "Truth": "FALSE", "Reference": ""},
    {"ID": 15, "Statement": "Ravana is depicted solely as a peaceful poet who never engaged in any battles.", "Truth": "FALSE", "Reference": ""},
    {"ID": 16, "Statement": "Rama’s exile lasted only one year rather than the traditionally recounted fourteen years.", "Truth": "FALSE", "Reference": ""},
    {"ID": 17, "Statement": "Sita and Rama were married in Lanka with Ravana acting as the priest for their wedding.", "Truth": "FALSE", "Reference": ""},
    {"ID": 18, "Statement": "Lakshmana is not mentioned at all in the Valmiki Ramayana.", "Truth": "FALSE", "Reference": ""},
    {"ID": 19, "Statement": "Bharata built a grand palace in Lanka following Rama’s victory over Ravana.", "Truth": "FALSE", "Reference": ""},
    {"ID": 20, "Statement": "Hanuman was the son of Ravana.", "Truth": "FALSE", "Reference": ""},
    {"ID": 21, "Statement": "Alliance with the vanara (monkey) army was instrumental in Rama’s victory over Lanka.", "Truth": "", "Reference": ""},
    {"ID": 22, "Statement": "Bharata accepted the throne without any longing for Rama’s return.", "Truth": "", "Reference": ""},
    {"ID": 23, "Statement": "Bharata declared war on Rama immediately after his exile.", "Truth": "", "Reference": ""},
    {"ID": 24, "Statement": "Bharata was the youngest of Rama’s brothers.", "Truth": "", "Reference": ""},
    {"ID": 25, "Statement": "Dasaratha wanted Lakshmana to become the king of Ayodhya.", "Truth": "", "Reference": ""},
    {"ID": 26, "Statement": "Dasaratha was still alive when Rama returned to Ayodhya after the exile.", "Truth": "", "Reference": ""},
    {"ID": 27, "Statement": "Dasharatha performs a Putrakameshti yajna to beget sons.", "Truth": "", "Reference": ""},
    {"ID": 28, "Statement": "Demoness Shurpanakha played a pivotal role in inciting the conflict between Rama and Ravana.", "Truth": "", "Reference": ""},
    {"ID": 29, "Statement": "Demoness Simhika tries to capture Hanuman during his flight but is killed by him.", "Truth": "", "Reference": ""},
    {"ID": 30, "Statement": "Dushana was the king of monkeys allied to Ravana.", "Truth": "", "Reference": ""},
    {"ID": 31, "Statement": "Hanuman betrayed Rama by divulging his battle plans to Ravana.", "Truth": "", "Reference": ""},
    {"ID": 32, "Statement": "Hanuman is born to Anjana and Kesari with blessings from the wind god, Vayu.", "Truth": "", "Reference": ""},
    {"ID": 33, "Statement": "Hanuman married Surasa, the serpent goddess.", "Truth": "", "Reference": ""},
    {"ID": 34, "Statement": "Hanuman never meets Sita in the entire epic.", "Truth": "", "Reference": ""},
    {"ID": 35, "Statement": "Hanuman was defeated by Sita in a contest of strength during their first meeting.", "Truth": "", "Reference": ""},
    {"ID": 36, "Statement": "Hanuman was taught the scriptures by Sage Surasa during his journey to Lanka.", "Truth": "", "Reference": ""},
    {"ID": 37, "Statement": "Hanuman’s leap to Lanka was achieved by riding a golden chariot rather than by his own power.", "Truth": "", "Reference": ""},
    {"ID": 38, "Statement": "Jatayu survived after fighting Ravana and later guided Rama to Sita.", "Truth": "", "Reference": ""},
    {"ID": 39, "Statement": "Jatayu tries to rescue Sita from Ravana and is mortally wounded.", "Truth": "", "Reference": ""},
    {"ID": 40, "Statement": "Kumbhakarna sleeps for six months at a time.", "Truth": "", "Reference": ""},
    {"ID": 41, "Statement": "Kumbhakarna was Ravana’s father.", "Truth": "", "Reference": ""},
    {"ID": 42, "Statement": "Lakshmana betrayed Rama by siding with Ravana during the war.", "Truth": "", "Reference": ""},
    {"ID": 43, "Statement": "Lakshmana is famous for his love of music and poetry rather than his loyalty to Rama.", "Truth": "", "Reference": ""},
    {"ID": 44, "Statement": "Lakshmana refused to accompany Rama into exile and stayed in Ayodhya.", "Truth": "", "Reference": ""},
    {"ID": 45, "Statement": "Lakshmana was not related to Rama but was merely an adopted son with no real bond.", "Truth": "", "Reference": ""},
    {"ID": 46, "Statement": "Malyavan was Ravana’s son who betrayed him.", "Truth": "", "Reference": ""},
    {"ID": 47, "Statement": "Malyavan, a rakshasa commander, advised Ravana to return Sita to avoid disaster.", "Truth": "", "Reference": ""},
    {"ID": 48, "Statement": "Mandavi, Bharata’s wife, is the daughter of King Kushadhvaja.", "Truth": "", "Reference": ""},
    {"ID": 49, "Statement": "Mandodari, Ravana’s queen, is portrayed as a noble and wise figure despite her husband’s deeds.", "Truth": "", "Reference": ""},
    {"ID": 50, "Statement": "Rama breaks Shiva’s bow to win Sita’s hand in marriage.", "Truth": "", "Reference": ""},
    {"ID": 51, "Statement": "Rama is described as having a golden complexion in his youth.", "Truth": "", "Reference": ""},
    {"ID": 52, "Statement": "Rama is frequently depicted riding a tiger instead of driving a chariot.", "Truth": "", "Reference": ""},
    {"ID": 53, "Statement": "Rama is known for his uncontrollable temper and unruly behavior.", "Truth": "", "Reference": ""},
    {"ID": 54, "Statement": "Rama is often depicted holding a bow and arrow, representing his warrior spirit.", "Truth": "", "Reference": ""},
    {"ID": 55, "Statement": "Rama kills the demoness Tataka in the forest.", "Truth": "", "Reference": ""},
    {"ID": 56, "Statement": "Rama refused to go into exile despite his father’s explicit orders.", "Truth": "", "Reference": ""},
    {"ID": 57, "Statement": "Rama uses the Brahmastra to kill Ravana.", "Truth": "", "Reference": ""},
    {"ID": 58, "Statement": "Rama was born in Lanka and later moved to Ayodhya.", "Truth": "", "Reference": ""},
    {"ID": 59, "Statement": "Rama’s departure for exile brought great sorrow to the people of Ayodhya.", "Truth": "", "Reference": ""},
    {"ID": 60, "Statement": "Rama’s exile lasted for fourteen years, as decreed by his stepmother Kaikeyi.", "Truth": "", "Reference": ""},
    {"ID": 61, "Statement": "Rama’s journey to Lanka was undertaken in a hot air balloon instead of by a constructed bridge.", "Truth": "", "Reference": ""},
    {"ID": 62, "Statement": "Rama’s reign is idealized as an era of peace and prosperity, often referred to as Rama Rajya.", "Truth": "", "Reference": ""},
    {"ID": 63, "Statement": "Rama’s victory over Ravana symbolizes the triumph of dharma (righteousness) over adharma (unrighteousness).", "Truth": "", "Reference": ""},
    {"ID": 64, "Statement": "Ramayana emphasizes the importance of following dharma over personal desires.", "Truth": "", "Reference": ""},
    {"ID": 65, "Statement": "Ramayana is traditionally divided into six books, known as Kandas.", "Truth": "", "Reference": ""},
    {"ID": 66, "Statement": "Ramayana was composed by the sage Valmiki, earning him the title of Adikavi (the first poet).", "Truth": "", "Reference": ""},
    {"ID": 67, "Statement": "Ravana is depicted as both a formidable warrior and a learned scholar in the Ramayana.", "Truth": "", "Reference": ""},
    {"ID": 68, "Statement": "Ravana is portrayed as a kind and gentle ruler throughout the Ramayana.", "Truth": "", "Reference": ""},
    {"ID": 69, "Statement": "Ravana is traditionally depicted with ten heads, symbolizing his vast knowledge and pride.", "Truth": "", "Reference": ""},
    {"ID": 70, "Statement": "Ravana voluntarily returned Sita to Rama out of sudden remorse without any conflict.", "Truth": "", "Reference": ""},
    {"ID": 71, "Statement": "Ravana was a demon (rakshasa) by birth.", "Truth": "", "Reference": ""},
    {"ID": 72, "Statement": "Ravana was defeated without any battle or struggle in the Ramayana.", "Truth": "", "Reference": ""},
    {"ID": 73, "Statement": "Ravana was undefeatable because he had a magical armor.", "Truth": "", "Reference": ""},
    {"ID": 74, "Statement": "Ravana’s son Indrajit uses magical weapons in battle.", "Truth": "", "Reference": ""},
    {"ID": 75, "Statement": "Sage Agastya blessed Rama during his early adventures, guiding his journey.", "Truth": "", "Reference": ""},
    {"ID": 76, "Statement": "Shatrughna is Rama's youngest brother.", "Truth": "", "Reference": ""},
    {"ID": 77, "Statement": "Shurpanakha tries to seduce Rama and Lakshmana but is disfigured by Lakshmana.", "Truth": "", "Reference": ""},
    {"ID": 78, "Statement": "Sita accompanied Rama into exile, symbolizing her unwavering loyalty.", "Truth": "", "Reference": ""},
    {"ID": 79, "Statement": "Sita cursed Ravana to be reborn as a demon again.", "Truth": "", "Reference": ""},
    {"ID": 80, "Statement": "Sita is described as having magical powers that allowed her to summon storms.", "Truth": "", "Reference": ""},
    {"ID": 81, "Statement": "Sita is found by King Janaka while he is ploughing the field.", "Truth": "", "Reference": ""},
    {"ID": 82, "Statement": "Sita is portrayed as a warrior who fought against Ravana on the battlefield.", "Truth": "", "Reference": ""},
    {"ID": 83, "Statement": "Sita left Rama willingly to live in Lanka.", "Truth": "", "Reference": ""},
    {"ID": 84, "Statement": "Sita was never abducted; she voluntarily went to Lanka.", "Truth": "", "Reference": ""},
    {"ID": 85, "Statement": "Sita was the biological daughter of Ravana.", "Truth": "", "Reference": ""},
    {"ID": 86, "Statement": "Sita’s abduction by Ravana led to the unification of various forces against the demon king.", "Truth": "", "Reference": ""},
    {"ID": 87, "Statement": "Sugreeva defeats Bali in a fist fight.", "Truth": "", "Reference": ""},
    {"ID": 88, "Statement": "Sugreeva, the monkey king, became a trusted ally of Rama against the forces of Lanka.", "Truth": "", "Reference": ""},
    {"ID": 89, "Statement": "Sugriva becomes king of Kishkindha with Rama’s help.", "Truth": "", "Reference": ""},
    {"ID": 90, "Statement": "Sugriva was hesitant to trust Rama until Rama helped him defeat Vali.", "Truth": "", "Reference": ""},
    {"ID": 91, "Statement": "Sumantra was a warrior who fought bravely in Lanka’s army.", "Truth": "", "Reference": ""},
    {"ID": 92, "Statement": "The monkey army in the Ramayana was led by Ravana himself.", "Truth": "", "Reference": ""},
    {"ID": 93, "Statement": "The monkey warrior Nala was an architect who helped build the Rama Setu (bridge).", "Truth": "", "Reference": ""},
    {"ID": 94, "Statement": "The vulture Sampati aided Hanuman by providing crucial information during his journey.", "Truth": "", "Reference": ""},
    {"ID": 95, "Statement": "Trijata comforts Sita during her captivity through prophetic dreams.", "Truth": "", "Reference": ""},
    {"ID": 96, "Statement": "Vali is killed by Rama from behind while fighting Sugriva.", "Truth": "", "Reference": ""},
    {"ID": 97, "Statement": "Valmiki composed the Ramayana while exiled on a deserted island with no guidance.", "Truth": "", "Reference": ""},
    {"ID": 98, "Statement": "Valmiki was a warrior king who fought alongside Rama in battle.", "Truth": "", "Reference": ""},
    {"ID": 99, "Statement": "Vibhisana was killed in the war between Rama and Ravana.", "Truth": "", "Reference": ""},
    {"ID": 100, "Statement": "Vibhishana, Ravana’s brother, defected to Rama’s side due to his commitment to righteousness.", "Truth": "", "Reference": ""}
]

# Convert the list of test statements to a DataFrame for easier handling
df_tests = pd.DataFrame(test_statements)

# Loop over each test statement
for idx, row in df_tests.iterrows():
    print(f"Test ID {row['ID']}: {row['Statement']}")  # Show which statement is being tested

    # Run the statement through the matcher
    result = match_statement(row['Statement'], df_aranya)

    # Print the expected result and the system's predicted result
    print("Expected Truth:", row['Truth'])
    print("Match Result:", result)
    print("-" * 60)  # Visual separator for readability

